<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTlaIoUx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTlaIoUx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTlaIoUx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTlaIoUx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTlaIoUx\App_KernelDevDebugContainer([
    'container.build_hash' => 'TlaIoUx',
    'container.build_id' => '5a252f22',
    'container.build_time' => 1608978120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTlaIoUx');
